### ISSUE TITLE
Missing return statements?

### ISSUE THREAD

**Issue by nvictus** [dovetail-genomics/coolR#2]
`seqinfo.cool`, `getBins` and `gi2is` don't return anything

**Comment by mblanche** [comment]
Implicit returns... Last evaluated line gets returned. I'll make it explicit for clarity.

**Comment by mblanche** [comment]
Pull the latest commit, fixed. Also, you might want to pull from the latest rhdf5 repo as they fixed the segmentation fault that I was experiencing

```
BiocManager::install('grimbough/rhdf5', ref = 'RELEASE_3_11')
```

**Comment by nvictus** [comment]
My R ignorance exposed :)

Thanks!

**Comment by mblanche** [comment]
No worries! R, like perl, has a lot of idiosyncrasies that can unsettle the python in you!

We’ll finish the examples and the docs and go for a BioConductor submission. Let me know if this is helpful in anyways. 

Sent from my iPad

-- Marco
